
let editingId=null;
function salesPage(){
 const sales=getSales().sort((a,b)=>new Date(b.date)-new Date(a.date));
 shell("Sales","sales",`<div class="card" id="new"><h2>${editingId?"Edit Sale":"Create New Sale"}</h2>
 <form id="saleForm"><div class="form-grid"><label>Customer Name<input id="custName" required></label><label>Contact Number<input id="custPhone" required inputmode="tel"></label><label>Email<input id="custEmail" type="email"></label><label>Address<textarea id="custAddress"></textarea></label></div>
 <h2 style="margin-top:22px">Items</h2><div id="items" class="sale-items"></div><button type="button" class="btn secondary" id="addItem">+ Add Product</button>
 <div class="form-grid three" style="margin-top:18px"><label>Discount<input id="discount" type="number" min="0" value="0"></label><label>Paid Amount<input id="paid" type="number" min="0" value="0"></label><label>Payment Status<select id="paymentStatus"><option>Paid</option><option>Partial</option><option>Remaining</option></select></label></div>
 <div class="card" style="margin-top:16px;background:#faf7f0"><div class="kpi-list"><div class="kpi"><span>Subtotal</span><strong id="subtotal">PKR 0.00</strong></div><div class="kpi"><span>Grand Total</span><strong id="grand">PKR 0.00</strong></div><div class="kpi"><span>Remaining</span><strong id="remaining">PKR 0.00</strong></div></div></div>
 <div class="form-actions"><button type="button" class="btn secondary" onclick="resetSale()">Clear</button><button class="btn primary" type="submit">Save Sale & Generate Invoice</button></div></form></div>
 <div class="card" style="margin-top:16px"><div class="toolbar"><input id="search" placeholder="Search invoice, customer or phone"><select id="statusFilter"><option value="">All Statuses</option><option>Paid</option><option>Partial</option><option>Remaining</option></select></div><div id="salesTable"></div></div>`);
 setupSaleForm();renderSalesTable();
}
function productOptions(selected){return getProducts().map(p=>`<option value="${p.id}" ${p.id===selected?"selected":""}>${esc(p.name)} ${esc(p.variant)} — ${money(p.price)}</option>`).join("")}
function addItem(data={}){const box=document.getElementById("items"),row=document.createElement("div");row.className="sale-row";row.innerHTML=`<label>Product<select class="item-product">${productOptions(data.productId)}</select></label><label>Qty<input class="item-qty" type="number" min="1" value="${data.quantity||1}"></label><label>Unit Price<input class="item-price" type="number" min="0" value="${data.unitPrice??(getProducts()[0]?.price||0)}"></label><label>Total<input class="item-total" readonly value="0"></label><button type="button" class="btn danger remove">Remove</button>`;box.appendChild(row);
 row.querySelector(".item-product").onchange=()=>{const p=getProducts().find(x=>x.id===row.querySelector(".item-product").value);row.querySelector(".item-price").value=p?.price||0;calc()};
 row.querySelector(".item-qty").oninput=calc;row.querySelector(".item-price").oninput=calc;row.querySelector(".remove").onclick=()=>{row.remove();calc()};calc();
}
function calc(){let sub=0;document.querySelectorAll(".sale-row").forEach(r=>{const q=Number(r.querySelector(".item-qty").value||0),p=Number(r.querySelector(".item-price").value||0),t=q*p;r.querySelector(".item-total").value=t.toFixed(2);sub+=t});const dis=Math.max(0,Number(document.getElementById("discount")?.value||0));const grand=Math.max(0,sub-dis);const paid=Math.min(grand,Math.max(0,Number(document.getElementById("paid")?.value||0)));document.getElementById("subtotal").textContent=money(sub);document.getElementById("grand").textContent=money(grand);document.getElementById("remaining").textContent=money(grand-paid);if(document.getElementById("paymentStatus"))document.getElementById("paymentStatus").value=paid>=grand&&grand>0?"Paid":paid>0?"Partial":"Remaining"}
function setupSaleForm(){document.getElementById("addItem").onclick=()=>addItem();document.getElementById("discount").oninput=calc;document.getElementById("paid").oninput=calc;addItem();document.getElementById("saleForm").onsubmit=saveSale;document.getElementById("search").oninput=renderSalesTable;document.getElementById("statusFilter").onchange=renderSalesTable}
function saveSale(e){e.preventDefault();const rows=[...document.querySelectorAll(".sale-row")];if(!rows.length)return;
 const items=rows.map(r=>{const p=getProducts().find(x=>x.id===r.querySelector(".item-product").value);const quantity=Number(r.querySelector(".item-qty").value),unitPrice=Number(r.querySelector(".item-price").value);return {productId:p.id,variant:p.variant,quantity,unitPrice,total:quantity*unitPrice}});const sub=items.reduce((a,i)=>a+i.total,0),discount=Math.max(0,Number(document.getElementById("discount").value||0)),grand=Math.max(0,sub-discount),paid=Math.max(0,Math.min(grand,Number(document.getElementById("paid").value||0)));
 const old=editingId?getSales().find(s=>s.id===editingId):null; const products=getProducts(); if(items.some(i=>{const p=products.find(x=>x.id===i.productId); return daysToExpiry(p?.expiryDate)!==null && daysToExpiry(p.expiryDate)<0})){alert("Cannot sell an expired product.");return} if(!old){for(const i of items){const p=products.find(x=>x.id===i.productId);if(i.quantity>p.stock){alert(`Insufficient stock for Honey ${p.variant}. Available: ${p.stock}`);return}}}
 const sale={id:editingId||crypto.randomUUID(),invoiceNo:old?.invoiceNo||nextInvoice(),date:old?.date||new Date().toISOString(),customer:{name:document.getElementById("custName").value.trim(),phone:document.getElementById("custPhone").value.trim(),email:document.getElementById("custEmail").value.trim(),address:document.getElementById("custAddress").value.trim()},items,subtotal:sub,discount,grandTotal:grand,paidAmount:paid,remainingAmount:grand-paid,paymentStatus:paid>=grand&&grand>0?"Paid":paid>0?"Partial":"Remaining"};
 let sales=getSales();if(old){ // restore old inventory then validate new stock
   old.items.forEach(i=>{const p=products.find(x=>x.id===i.productId);if(p)p.stock+=i.quantity});
   for(const i of items){const p=products.find(x=>x.id===i.productId);if(i.quantity>p.stock){alert(`Insufficient stock for Honey ${p.variant}.`);old.items.forEach(x=>{const p2=products.find(y=>y.id===x.productId);if(p2)p2.stock-=x.quantity});return}}
   sales=sales.map(s=>s.id===editingId?s:s);
   const idx=sales.findIndex(s=>s.id===editingId);sales[idx]=sale;
 }else sales.push(sale);
 items.forEach(i=>{const p=products.find(x=>x.id===i.productId);p.stock-=i.quantity});saveProducts(products);saveSales(sales);recomputeCustomers();editingId=null;toast("Sale saved successfully.");openInvoice(sale.id);salesPage();
}
function renderSalesTable(){const q=(document.getElementById("search")?.value||"").toLowerCase(),f=document.getElementById("statusFilter")?.value||"";let ss=getSales().filter(s=>(!q||s.invoiceNo.toLowerCase().includes(q)||s.customer.name.toLowerCase().includes(q)||s.customer.phone.toLowerCase().includes(q))&&(!f||s.paymentStatus===f));document.getElementById("salesTable").innerHTML=ss.length?`<div class="table-wrap"><table class="table"><thead><tr><th>Invoice</th><th>Date</th><th>Customer</th><th>Total</th><th>Paid</th><th>Remaining</th><th>Status</th><th>Actions</th></tr></thead><tbody>${ss.map(s=>`<tr><td>${s.invoiceNo}</td><td>${dateStr(s.date)}</td><td>${esc(s.customer.name)}</td><td>${money(s.grandTotal)}</td><td>${money(s.paidAmount)}</td><td>${money(s.remainingAmount)}</td><td>${statusBadge(s.paymentStatus)}</td><td class="actions"><button class="btn secondary" onclick="openInvoice('${s.id}')">Invoice</button><button class="btn secondary" onclick="editSale('${s.id}')">Edit</button><button class="btn danger" onclick="deleteSale('${s.id}')">Delete</button></td></tr>`).join("")}</tbody></table></div>`:`<div class="empty">No sales records found.</div>`}
function editSale(id){const s=getSales().find(x=>x.id===id);if(!s)return;editingId=id;document.getElementById("custName").value=s.customer.name;document.getElementById("custPhone").value=s.customer.phone;document.getElementById("custEmail").value=s.customer.email;document.getElementById("custAddress").value=s.customer.address;document.getElementById("discount").value=s.discount;document.getElementById("paid").value=s.paidAmount;document.getElementById("items").innerHTML="";s.items.forEach(addItem);calc();scrollTo({top:0,behavior:"smooth"})}
function deleteSale(id){if(!confirm("Delete this sale? Inventory and totals will be restored."))return;const ss=getSales(),s=ss.find(x=>x.id===id),ps=getProducts();s.items.forEach(i=>{const p=ps.find(x=>x.id===i.productId);if(p)p.stock+=i.quantity});saveProducts(ps);saveSales(ss.filter(x=>x.id!==id));recomputeCustomers();toast("Sale deleted.");renderSalesTable()}
function resetSale(){editingId=null;document.getElementById("saleForm").reset();document.getElementById("items").innerHTML="";addItem();calc()}
salesPage();
