
function settingsPage(){const s=getSettings(),a=getAdmin();shell("Settings","settings",`<div class="grid two"><div class="card"><h2>Company Information</h2><form id="companyForm"><label>Company Name<input id="companyName" value="${esc(s.companyName)}" required></label><label>Address<textarea id="companyAddress">${esc(s.companyAddress)}</textarea></label><label>Phone<input id="companyPhone" value="${esc(s.companyPhone)}"></label><label>Email<input id="companyEmail" type="email" value="${esc(s.companyEmail)}"></label><button class="btn primary">Save Company Settings</button></form></div>
<div class="card"><h2>Admin Credentials</h2><form id="adminForm"><label>Username<input id="adminUsername" value="${esc(a.username)}" required></label><label>New Password<input id="adminPassword" type="password" placeholder="Enter new password" required></label><button class="btn primary">Update Credentials</button></form><hr style="border:0;border-top:1px solid var(--line);margin:25px 0"><h2>Backup & Restore</h2><div class="actions"><button class="btn secondary" id="export">Export Backup</button><label class="btn secondary" style="margin:0;cursor:pointer">Import Backup<input id="import" type="file" accept=".json" hidden></label></div><button class="btn danger" id="clear" style="margin-top:15px">Clear All Data</button></div></div>
<div class="card" style="margin-top:16px"><h2>Product Prices</h2><p class="muted">Manage prices and stock from the Products page.</p><a class="btn secondary" href="products.html">Open Products</a></div>`);
document.getElementById("companyForm").onsubmit=e=>{e.preventDefault();saveSettings({...getSettings(),companyName:document.getElementById("companyName").value.trim(),companyAddress:document.getElementById("companyAddress").value.trim(),companyPhone:document.getElementById("companyPhone").value.trim(),companyEmail:document.getElementById("companyEmail").value.trim()});toast("Company settings saved.");};
document.getElementById("adminForm").onsubmit=e=>{e.preventDefault();saveAdmin({username:document.getElementById("adminUsername").value.trim(),password:document.getElementById("adminPassword").value});toast("Admin credentials updated.");document.getElementById("adminPassword").value=""};
document.getElementById("export").onclick=()=>downloadJSON(`honey-management-backup-${new Date().toISOString().slice(0,10)}.json`,{products:getProducts(),sales:getSales(),customers:getCustomers(),settings:getSettings(),admin:getAdmin(),counter:localStorage.getItem(KEYS.counter)});
document.getElementById("import").onchange=e=>{const file=e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!d.products||!d.sales||!d.settings)throw Error();write(KEYS.products,d.products);write(KEYS.sales,d.sales);write(KEYS.customers,d.customers||[]);write(KEYS.settings,d.settings);if(d.admin)write(KEYS.admin,d.admin);if(d.counter)localStorage.setItem(KEYS.counter,d.counter);recomputeCustomers();toast("Backup restored successfully.");setTimeout(()=>location.reload(),500)}catch(_){alert("Invalid backup file.")}};r.readAsText(file)};
document.getElementById("clear").onclick=()=>{if(confirm("WARNING: This will permanently remove sales, customers, invoices and inventory records from this browser. Continue?")&&confirm("Are you absolutely sure?")){resetAll();toast("All data cleared.");setTimeout(()=>location.reload(),500)}};
}
settingsPage();
